### ISSUE TITLE
COOL VPN often crashes

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#102]
# 🐛 Bug Report

Some assessors report that the COOL VPN often crashes.

**Comment by jsf9k** [comment]
Got some more clarification from the Fed lead:

This behavior was noticed during the period when @dav3r and I were seeing AWS internal networking glitches last week.  @dav3r and I both noticed that AWS access via the control plane was sluggish and very occasionally unavailable Tuesday-Wednesday of last week.

**Comment by jsf9k** [comment]
cc @brubach

**Comment by dav3r** [comment]
@brubach or @jasonhillva: Has anyone observed a VPN disruption on any date other than Oct. 15, 2020 (when @brubach mentioned it to me)?  

If not, I propose that we chalk this up to a temporary AWS service disruption and close out this issue.  We can always re-open if it happens again.

**Comment by dav3r** [comment]
Since we have not heard of any additional VPN disruptions from COOL users, I am closing this issue.
