### ISSUE TITLE
outbound mail blocked (env4.TeamServer)

### ISSUE THREAD

**Issue by sporac** [cisagov/cool-system#108]
We've built the phishing infrastructure. In testing testing, it appears that the team server cannot sent mail.

**Comment by jsf9k** [comment]
This is in env4 in testing?

**Comment by sporac** [comment]
Production

**Comment by jsf9k** [comment]
OK, I think I know the problem there.  By default AWS throttles mail ports.  I will request that be turned off now.

**Comment by jsf9k** [comment]
I received an email from AWS on Friday night stating that they had removed the port throttle.  @sporac, please let me know if your next test is successful.

**Comment by jsf9k** [comment]
According to @sporac, "Things are working as expected."  I'll go ahead and close this issue.
