### ISSUE TITLE
Incorporate Domain-Manager in the COOL

### ISSUE THREAD

**Issue by zenine07** [cisagov/cool-system#114]
Incorporate domain-manager into the COOL in a separate AWS account. The various components of the app are defined in the following repositories.

- domain-manager
- domain-manager-ui
- domain-manager-api

The terraform and builds will occur in the domain-manager-cicd repo which will need access to a staging and production COOL account for deployments.

Tasks To Do:
- [x] Create new ~~"User Services"~~ "Domain Manager" AWS accounts via Control Tower
  - [x] `Domain Manager (Staging)`
  - [x] `Domain Manager (Production)`
- [x] Provision Domain Manager AWS accounts via new [cisagov/cool-accounts-domain-manager](https://github.com/cisagov/cool-accounts-domain-manager) repo
  - [x] Staging
  - [x] Production
- [x] ~~Create new repo `cisagov/cool-accounts-userservices` and bootstrap User Services accounts - see https://github.com/cisagov/cool-accounts-userservices/pull/1~~
- [x] Allow Shared Services Transit Gateway to talk to ~~User Services~~ Domain Manager accounts - see https://github.com/cisagov/cool-sharedservices-networking/pull/42
  - [x] Apply change in Shared Services (Staging)
  - [x] Apply change in Shared Services (Production)
- [x] Create new repo [`cisagov/cool-domain-manager-networking`](https://github.com/cisagov/cool-domain-manager-networking) for core networking (VPC, subnets, TGW access, routing, etc) (similar to https://github.com/cisagov/cool-userservices-networking/pull/1)
- [x] Provision ~~User Services~~ Domain Manager networking with [`cisagov/cool-domain-manager-networking`](https://github.com/cisagov/cool-domain-manager-networking) - see https://github.com/cisagov/cool-domain-manager-networking/pull/2
  - [x] Staging
  - [x] Production
- [x] Create single role & policy in [`cisagov/cool-accounts`](https://github.com/cisagov/cool-accounts)(`terraform` subdirectory) that allows read/write access to Domain Manager-related Terraform state resources - see https://github.com/cisagov/cool-accounts/pull/73
- [x] Split auditor IAM code out of [`cisagov/cool-users-non-admin`](https://github.com/cisagov/cool-users-non-admin) and into new repo [`cisagov/cool-auditor-iam`](https://github.com/cisagov/cool-auditor-iam) - see https://github.com/cisagov/cool-users-non-admin/pull/13 and https://github.com/cisagov/cool-auditor-iam/pull/1
- [x] Move PCA users from [`cisagov/cool-users-pca`](https://github.com/cisagov/cool-users-pca) to [`cisagov/cool-users-non-admin`](https://github.com/cisagov/cool-users-non-admin)
  - [x] Add PCA users to [`cisagov/cool-users-non-admin`](https://github.com/cisagov/cool-users-non-admin) tfvars file
  - [x] Use `terraform import` to bring PCA users into TF state for  [`cisagov/cool-users-non-admin`](https://github.com/cisagov/cool-users-non-admin)
  - [x] Update [`cisagov/cool-users-non-admin`](https://github.com/cisagov/cool-users-non-admin) to support users that are not allowed to administer their own accounts (e.g. `ghactions-pca`) - see https://github.com/cisagov/cool-users-non-admin/pull/15
- [x] Rename [`cisagov/cool-users-pca`](https://github.com/cisagov/cool-users-pca) to `cisagov/cool-pca-iam`
- [x] Update [`cisagov/cool-pca-iam`](https://github.com/cisagov/cool-pca-iam) - see https://github.com/cisagov/cool-pca-iam/pull/7
  - [x] Update backend key to reflect new repo name (`cisagov/cool-pca-iam`)
  - [x] Remove user creation code from `cisagov/cool-pca-iam` (replace with looking up existing users now created by `cisagov/cool-users-non-admin`)
  - [x] Ensure `cisagov/cool-pca-iam` is consistent with [`cisagov/cool-auditor-iam`](https://github.com/cisagov/cool-auditor-iam)
- [x] Run `terraform apply` in `cisagov/cool-pca-iam` and ensure state is correct
- [x] Provision Domain Manager CI/CD IAM account in [`cisagov/cool-users-non-admin`](https://github.com/cisagov/cool-users-non-admin)
- [x] Move `ProvisionDomainManager` permissions from [`cisagov/cool-accounts-userservices`](https://github.com/cisagov/cool-accounts-userservices) to [`cisagov/cool-domain-manager-networking`](https://github.com/cisagov/cool-domain-manager-networking) and attach to `ProvisionAccount` role.
  - [x] Delete `ProvisionDomainManager` role previously created in https://github.com/cisagov/cool-accounts-userservices/pull/3 and apply in Staging and Production - see https://github.com/cisagov/cool-accounts-userservices/pull/6
  - [x] Apply `cisagov/cool-domain-manager-networking` Terraform  in Staging
  - [x] Apply `cisagov/cool-domain-manager-networking` Terraform in Production
- [x] Create access key for Domain Manager CI/CD IAM account and provide credentials to INL team
- [x] Provision COOL IAM group for Domain Manager Terraformers in Users account
  - [x] Create new repo `cisagov/cool-domain-manager-iam`
  - [x] Add users listed in a tfvars file
  - [x] Attach policies allowing assumption of `ProvisionDomainManager`, `AccessDomainManagerTerraformBackend`, and `AssumeProvisionPrivateDNSRecords` roles to provisioners group in `cisagov/cool-domain-manager-iam` - see https://github.com/cisagov/cool-domain-manager-iam/pull/2
  - [x] Remove policy allowing assumption of `ProvisionDomainManager` roles from provisioners group in `cisagov/cool-domain-manager-iam` - see https://github.com/cisagov/cool-domain-manager-iam/pull/5
  - [x] Attach policies allowing read-only access of Terraform state for [`cool-sharedservices-networking`](https://github.com/cisagov/cool-sharedservices-networking) and [`cool-userservices-networking`](https://github.com/cisagov/cool-userservices-networking) - see https://github.com/cisagov/cool-domain-manager-iam/pull/4
  - [x] Remove policy allowing read-only access of Terraform state for [`cool-userservices-networking`](https://github.com/cisagov/cool-userservices-networking) - see https://github.com/cisagov/cool-domain-manager-iam/pull/5
  - [x] Re-run `terraform apply` in `cisagov/cool-domain-manager-iam` after changes above have been made
- [x] Create roles for Lambda & ECS (Staging) - ~~see https://github.com/cisagov/cool-accounts-userservices/pull/5~~ This will now be handled by @zenine07 in [`cisagov/domain-manager-cicd`](https://github.com/cisagov/domain-manager-cicd)
  - [x] Lambda Execution Role
  - [x] ECS Execution Role
  - [x] ECS Task Role
- [x] Create roles for Lambda & ECS (Production)
- [x] Move Terraform for items below from [`cool-userservices-dns`](https://github.com/cisagov/cool-userservices-dns) to new repo [`cisagov/cool-domain-manager-networking`](https://github.com/cisagov/cool-domain-manager-networking) - see https://github.com/cisagov/cool-domain-manager-networking/pull/2:
  - [x] ACM certificate for `domain-manager.staging.cool.cyber.dhs.gov` in Domain Manager (Staging) account
  - [x] ACM certificate for `domain-manager.cool.cyber.dhs.gov` in Domain Manager (Production) account
  - [x] Certificate validation records in public `cyber.dhs.gov` zone (DNS account)
  - [x] Delete resources above created during testing of [`cool-userservices-dns`](https://github.com/cisagov/cool-userservices-dns)
  - [x] Modify https://github.com/cisagov/cool-userservices-dns/pull/2 to be generic so it will be ready for whatever user service comes along next - see https://github.com/cisagov/cool-userservices-dns/pull/2
  - [x] Recreate resources above with [`cisagov/cool-domain-manager-networking`](https://github.com/cisagov/cool-domain-manager-networking) - https://github.com/cisagov/cool-domain-manager-networking/pull/2
- [x] Attach policy allowing read-only access of Terraform state for [`cool-domain-manager-networking`](https://github.com/cisagov/cool-domain-manager-networking) to Domain Manager provisioner users group - see https://github.com/cisagov/cool-domain-manager-iam/pull/5

**Comment by dav3r** [comment]
I think we are all done with the work for this issue. @zenine07 - please open new issues if any further work is required.
