### ISSUE TITLE
Guacamole unaccessible in env4

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#119]
# 🐛 Bug Report

This morning, @sporac reported the following:
> Everyone on the team is getting an Unauthorized message when attempting to access systems in env4.
Additional information: I was connected to an existing session and everything was working fine until the VPN dropped. (I had removed my PIV at access Lan-A.) Now, I can no longer access the environment.

@dav3r and I investigated.  We saw the same issue as @sporac using our administrative credentials.

We attempted the following without success:
* Restart Apache service
* Restart `guacamole-composition` service
* Run the `unenroll` portion of the `/usr/local/sbin/00_setup_freeipa.sh` script.  That failed with the output `No permission to join this host to the IPA domain`.  A direct running of `ipa-join -d --unenroll` indicated that the issue is `
Insufficient access: Insufficient 'write' privilege to the 'krbLastPwdChange' attribute of entry 'krbprincipalname=http/guac.env4.cool.cyber.dhs.gov@cool.cyber.dhs.gov,cn=services,cn=accounts,dc=cool,dc=cyber,dc=dhs,dc=gov'`.

This last bullet indicated that the root issue was that the guacamole's enrollment to the domain was somehow messed up.  I did the following:
1. `sudo ipa-client-install --uninstall`
1. Removed the env4 guacamole host from the domain via the FreeIPA web UI
1. `sudo ./00_setup_freeipa.sh`
1. `sudo ./01_setup_http_service.sh`
1. `sudo ./02_setup_guacamole_services.sh`

At this point @dav3r and I were able to connect to other machines via the guacamole instance, although @dav3r had to re-`kinit`.

**Comment by jsf9k** [comment]
We still don't know exactly why this occurred.  I suppose it is possible that something funky happened while I was upgrading the FreeIPA cluster last Friday, although all the other guacamole servers in the other envs are fine.

We will keep an eye out for this in the future.

**Comment by jsf9k** [comment]
This may have been another symptom of the FreeIPA replication failure that was also the root cause behind #129.

**Comment by dav3r** [comment]
We have not seen this issue again after the initial occurrence.  I propose that we close this issue and reopen it if it occurs again.

**Comment by dav3r** [comment]
Closing due to lack of further occurrences.
