### ISSUE TITLE
Bootstrap Staging accounts

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-system#12]
Bootstrap the new Staging AWS accounts to the point that they are usable by us.

**Comment by jsf9k** [comment]
Images and Shared Services have been bootstrapped via [cisagov/cool-accounts](https://github.com/cisagov/cool-accounts).  The corresponding `staging.tfvars` files have been committed to [cisagov/cool-tfvars](https://github.com/cisagov/cool-tfvars).  I have also deployed [cisagov/cool-sharedservices-networking](https://github.com/cisagov/cool-sharedservices-networking) to staging.

I created `staging-accounts` in [cisagov/cool-aws-profiles](https://github.com/cisagov/cool-aws-profiles).  The idea is that you swap filenames in your [cisagov/aws-profile-sync](https://github.com/cisagov/aws-profile-sync) comment line when switching between environments.

I'm working on deploying [cisagov/cool-sharedservices-freeipa](https://github.com/cisagov/cool-sharedservices-freeipa) and [cisagov/cool-sharedservices-openvpn](https://github.com/cisagov/cool-sharedservices-openvpn) to staging.  This requires the changes that @felddy recently made in cisagov/kali-packer#10 to be backported to [cisagov/skeleton-packer-cool](https://github.com/cisagov/skeleton-packer-cool) so they can flow down to [cisagov/freeipa-server-packer](https://github.com/cisagov/freeipa-server-packer) and [cisagov/openvpn-packer](https://github.com/cisagov/openvpn-packer).
