### ISSUE TITLE
Missing Software on Kali Image

### ISSUE THREAD

**Issue by justinforbes** [cisagov/cool-system#122]
# 🐛 Bug Report

The Kali images are missing the following programs:
- Thunderbird email client
- BurpSuitePro

## Expected behavior

Thunderbird is needed to verify the email server is working as well as to establish how many phishing emails bounced.
BurpSuitePro is needed for testing web applicaitons.

**Comment by jsf9k** [comment]
* Thunderbird is being added as part of [cisagov/kali-packer#44](https://github.com/cisagov/kali-packer/pull/44), which is in progress.
* The addition of BurpSuitePro is a duplicate of #34.
