### ISSUE TITLE
Some non-dev folks cannot log into guacamole in some assessment environments

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#129]
# 🐛 Bug Report

We have seen a few cases where _some_ non-dev folks could not log into guacamole in _some_ assessment environments.

* On Friday, November 20, one of @sporac's assessors could not access guacamole in env8 even though I had _just_ added her to the appropriate user group on `ipa0`.
* On Monday, November 23, another of @sporac's assessors could not access guacamole in env8 even though on Friday I had added him to the appropriate user group on `ipa0`.  @hillaryj, @mcdonnnj, and I spent several hours debugging the issue with the assessor and @bra1ncramp to no avail.  We thought the issue was perhaps due to a difference between the Jamf and non-Jamf laptops.  [@hillaryj documented the actions we took to fully synchronize her Jamf laptop](https://github.com/cisagov/cool-system/wiki/Guac-connection-issue-debug-notes).
* On Wednesday, November 25, @KyleEvers was unable to access guacamole in env9 even though I had just created the environment for him and added him to the appropriate group on `ipa0`.

In all cases I verified that, according to the HBAC rules in place on `ipa0`, all the users in question should have been able to access guacamole in their respective environments.

## Expected behavior

Any user who is in the appropriate group user group in FreeIPA should be able to access guacamole in an assessment environment.

**Comment by jsf9k** [comment]
I realized the source of the issue this morning while debugging why @KyleEvers was unable to access guacamole.  Looking at the FreeIPA web UI on `ipa1` and `ipa2` I could see that those two servers were missing all changes recently made on `ipa0`.  When I noticed this I immediately modified the FreeIPA DNS records to stop advertising `ipa1` and `ipa2`, but @KyleEvers continued to see the problem because some Kerberos/FreeIPA requests were still going to `ipa1` and `ipa2`.  I believe this was because the TTL for the DNS records in question is set to `86400` in production, so the old values were still alive in local DNS caches.  Eventually the caches expired and @KyleEvers was able to access the guacamole instance in his environment.

Upon inspection, the topology and replication agreements between `ipa0`, `ipa1`, and `ipa2` appeared to be OK.  Using the command `sudo ipa-replica-manage list-ruv` I was able to see some old vectors from before the last FreeIPA cluster upgrade.  I removed those using `sudo ipa-replica-manage clean-dangling-ruv` but `ipa1` and `ipa2` did not start replicating against `ipa0` again.  Finally, I was able to force the replication to begin again by running `sudo ipa-replica-manage re-initialize --from ipa0.cool.cyber.dhs.gov` on both `ipa1` and `ipa2`.  At that point I added and removed a dummy test user from `ipa0` and verified that the replication was again working.

**Comment by jsf9k** [comment]
Question for @cisagov/team-ois:  Should we reduce the TTL for FreeIPA-related DNS records in production, at least for now?

**Comment by jsf9k** [comment]
I added [this section](https://github.com/cisagov/cool-system/wiki/Upgrading-the-FreeIPA-cluster#clean-any-dangling-replica-update-vectors-ruvs) to the FreeIPA cluster upgrade documentation.  This should remove any dangling RUVs that are present immediately after a FreeIPA upgrade, and hopefully prevent this issue from happening again.

**Comment by hillaryj** [comment]
Awesome, congrats on finding the cause!

**Comment by jsf9k** [comment]
Closing this issue since I believe the problem is fixed.
