### ISSUE TITLE
Merge skeleton-packer and skeleton-packer-cool

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-system#14]
[skeleton-packer](https://github.com/cisagov/skeleton-packer) should be usable in a single-account setup, as well as in a multiple-account setup (like the COOL).  Take the goodies from [skeleton-packer-cool](https://github.com/cisagov/skeleton-packer-cool) and apply them to [skeleton-packer](https://github.com/cisagov/skeleton-packer) in an intelligent way so that everything Just Works in both cases.

**Comment by jsf9k** [comment]
Hasn't this work already been done, modulo retiring the skeleton-packer-cool repo?

**Comment by dav3r** [comment]
> Hasn't this work already been done, modulo retiring the skeleton-packer-cool repo?

Yes, I believe we are able to now retire the [`skeleton-packer-cool`](https://github.com/cisagov/skeleton-packer-cool) repo.  I will take care of that, unless there are any objections.

**Comment by dav3r** [comment]
[`skeleton-packer-cool`](https://github.com/cisagov/skeleton-packer-cool) has been archived.  

From now on, [`skeleton-packer`](https://github.com/cisagov/skeleton-packer) is The Way.
