### ISSUE TITLE
Share Mount Issue

### ISSUE THREAD

**Issue by brubach** [cisagov/cool-system#149]
The EFS share in env6 was mounted on all Kali instances, but data put in the folders was not displaying across them.  Removing the content from the EFS share, remounting the share, and re-adding the content seemed to fix this issue.

It is important to refresh the folder or terminal you are in to see the updated content.

**Comment by jsf9k** [comment]
@brubach, I suspect the advice I gave you to unmount, re-copy, and re-mount was unnecessary.  I misunderstood and thought you were suffering from issue cisagov/cool-assessment-terraform#85.

We'll try to reproduce this and determine the exact cause.  @brubach, if you see this again please note what you see in these three cases:
1. In the file browser window on the XFCE desktop
1. `ls ~vnc/share`
1. `ls /share`

**Comment by dav3r** [comment]
@brubach - Have you seen this issue lately?  If not, I think we can close this issue out.
