### ISSUE TITLE
Bake Guacamole Docker images into the Guacamole AMI

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#158]
# 💡 Summary #

We should bake the Docker images required by the Guacamole Docker composition into the Guacamole AMI.

## Motivation and context ##

This would allow us to get rid of the NAT gateway in the operations subnet of the assessment environments.

## Acceptance criteria ##

- [x] The Docker images required by the Guacamole Docker composition are baked into the Guacamole AMI.
- [x] The NAT gateway is removed from the operations subnet.
- [x] The Guacamole instance continues to function as it did before, despite the lack of access to the external internet.

**Comment by jsf9k** [comment]
Another thought is moving the Docker images from DockerHub to AWS ECR and adding the required VPC endpoint(s) to pull Docker images from that service.  This would allow us to pull the Docker images at run time _without_ having to pre-pull them into the AMI.

What do you think @felddy and @dav3r?  I think this is a better solution because you will get the latest Docker images when the AMI launches, as opposed to whatever the latest images were when the AMI was built.

**Comment by dav3r** [comment]
I like that idea, though I don't exactly understand how it would work.  When our instance requests the Guacamole Docker image from ECR, can ECR automatically pull in the latest image from DockerHub at that time?  Or do we have to tell ECR to check DockerHub for new a Guacamole image every so often and if it finds one, pull it from DockerHub into ECR?

**Comment by jsf9k** [comment]
> I like that idea, though I don't exactly understand how it would work. When our instance requests the Guacamole Docker image from ECR, can ECR automatically pull in the latest image from DockerHub at that time? Or do we have to tell ECR to check DockerHub for new a Guacamole image every so often and if it finds one, pull it from DockerHub into ECR?

We would push the images up to ECR instead or (or in addition to) Docker Hub.

**Comment by dav3r** [comment]
Got it- I understand now- sounds like a good solution to me.  The only (minimal) downside I see is that we will need an additional process to track the Guacamole Docker Hub images more closely so we know if/when we need to push a new one up to ECR.  Seems like a good trade-off in return for getting rid of the NAT gateway in our assessment environments.

**Comment by jsf9k** [comment]
> The only (minimal) downside I see is that we will need an additional process to track the Guacamole Docker Hub images more closely so we know if/when we need to push a new one up to ECR.

Can't we just push new images to both repositories when merging PRs?

**Comment by jsf9k** [comment]
> > The only (minimal) downside I see is that we will need an additional process to track the Guacamole Docker Hub images more closely so we know if/when we need to push a new one up to ECR.
> 
> Can't we just push new images to both repositories when merging PRs? I don't see that as a downside at all.

@dav3r pointed out to me that we currently pull `guacamole/guacamole:latest` from Docker Hub, and that is the complication he is thinking of.  He was way ahead of me on that one.

**Comment by jsf9k** [comment]
See:
* cisagov/ansible-role-guacamole#26

**Comment by jsf9k** [comment]
Resolved via:
* cisagov/ansible-role-guacamole#26
* cisagov/guacamole-packer#37
* cisagov/cool-assessment-terraform#98
