### ISSUE TITLE
Rename AWS accounts to include "type".  Delete old accounts.

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#16]
# 🐛 Bug Report

Right now, there is no good way to tell what "type" (production, staging, alpha, beta, etc.) an account is.  I could split on a space character and take the last element, and then make it "production" if the length of the split is one, but some of our account names are multi-word.  I really think it makes sense to include the account "type" in the account name.  I suggest something of the form "Shared Services (Staging)".

Look at [the abomination I have created to deal with just production and staging](https://github.com/cisagov/cool-sharedservices-networking/blob/bugfix/tgw-sharing/transitgateway.tf#L49-L71).

**Comment by felddy** [comment]
We've also agreed to delete all the old accounts except the old `Users` account.

**Comment by felddy** [comment]
The deletions are now all cleared in SSO.  I'm starting to do the renames:

https://aws.amazon.com/premiumsupport/knowledge-center/change-organizations-name/

**Comment by felddy** [comment]
These changes are completed.
