### ISSUE TITLE
Build laptop-deployable images in AWS

### ISSUE THREAD

**Issue by felddy** [cisagov/cool-system#17]
Collecting information and requirements about creating images in the cloud for deployment on local hardware (laptops). 

Links from related emails and chats:

1. https://www.infralovers.com/en/articles/2019/10/15/automated-vmware-templates-with-hashicorp-packer/
1. https://github.com/StefanScherer/packer-windows
1. https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport_image.html
1. https://aws.amazon.com/ec2/vm-import/
1. https://packer.io/docs/builders/index.html

**Comment by felddy** [comment]
@circuitswitch has some information about applying license keys to marketplace AMIs, which then allows export...

**Comment by circuitswitch** [comment]
Based on this article from AWS, theoretically we should be able to export a Windows AMI built from AWS AMIs or the Marketplace.  We just have to change the activation key to our VLSC key.  However, this needs testing to verify.
https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html
Look under licensing for Windows

"The following rules apply when you use your BYOL Microsoft license, either through MSDN or Windows Software Assurance Per User:"

"Activate using Microsoft keys that you provide or which are used in your key management system."

**Comment by mzack5020** [comment]
> Based on this article from AWS, theoretically we should be able to export a Windows AMI built from AWS AMIs or the Marketplace. We just have to change the activation key to our VLSC key. However, this needs testing to verify.
> https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html
> Look under licensing for Windows
> 
> "The following rules apply when you use your BYOL Microsoft license, either through MSDN or Windows Software Assurance Per User:"
> 
> "Activate using Microsoft keys that you provide or which are used in your key management system."

[9:59 AM] Chesney, Brian
    
https://github.com/cisagov/cool-system/issues
cisagov/cool-systemThe Cloud Optimized Operational Lab (COOL) system. Contribute to cisagov/cool-system development by creating an account on GitHub.github.com

**Comment by dav3r** [comment]
> Based on this article from AWS, theoretically we should be able to export a Windows AMI built from AWS AMIs or the Marketplace.

According to ["Exporting a VM Directly from an Amazon Machine Image (AMI)"](https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport_image.html#vmexport-limits):

> "You can't export an image if it contains third-party software provided by AWS. For example, VM Export cannot export Windows or SQL Server images, or any image created from an image in the AWS Marketplace."

If I'm reading this correctly, it means that we cannot create a Windows AMI, then export it as a VM. 

However, I don't think there are any issues if we use Packer (running on an AWS instance) to create:
-  Windows AMIs (using the [amazon builder for Packer](https://www.packer.io/docs/builders/amazon/))
- Windows VMs (using the [vmware builder for Packer](https://www.packer.io/docs/builders/vmware/)) and store them in an S3 bucket

That gives us the same Windows image that can either be spun up on an EC2 instance (for use in the COOL) or pulled in from the S3 bucket (for use on an assessment laptop).  I believe a solution like this will meet our needs, but please chime in if I'm misunderstanding something.

Side note: The versions of Windows AMIs available from Amazon [do not include Windows 7 or Windows 10](https://aws.amazon.com/windows/resources/amis/) (those are the two versions mentioned in the COOL requirements for Assessments).
