### ISSUE TITLE
Open ports for assessment instance types

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#170]
# 🐛 Summary #
 
An assessor noticed that port 50050 was open to the internet on a teamserver.  He says this should not be the case.  I shared with him the fact that the following ports are currently opened to the internet for all "scanner" instance types (Teamserver, Kali, GoPhish, and Nessus):

| Protocol | Port or Port Range |
| --- | --- |
| TCP | 25 |
| TCP | 53 |
| TCP | 80 |
| TCP | 443 |
| TCP | 587 |
| TCP | 993 |
| TCP | 8000-8833 |
| TCP | 8835-8999 |
| TCP | 50050 |
| UDP | 53 |
| UDP | 8080 |

He stated that some of those open ports are necessary, but only for some instance types.  We should modify the COOL assessment environment to by default only open the necessary ports for each instance type.  The actual open ports for each instance type can always be changed per assessment if desired.

# Gather information #

To nail down what ports should be open to the internet for what instance types, let's fill out the following tables.  **Note that _italicized_ lines indicate ports that should be opened only internal to the assessment environment.**

## GoPhish ##

| Protocol | Port or Port Range | Reason Needed |
| --- | --- | --- |
| _TCP_ | _22_ | _ssh from Guacamole_ |
| TCP | 25 | Mail |
| TCP | 80 | Phishing landing pages |
| TCP | 443 | Phishing landing pages |
| TCP | 587 | Mail |
| _TCP_ | _5901_ | _vnc from Guacamole_ |

## Kali ##

| Protocol | Port or Port Range | Reason Needed |
| --- | --- | --- |
| _TCP_ | _22_ | _ssh from Guacamole_ |
| _TCP_ | _5901_ | _vnc from Guacamole_ |
| TCP | 8000-8999 | Ports that can be manipulated in the event that we need to open a listener for capturing testing traffic from a target.  Default state is not listening. |

## Nessus ##

| Protocol | Port or Port Range | Reason Needed |
| --- | --- | --- |
| _TCP_ | _22_ | _ssh from Guacamole_ |
| _TCP_ | _5901_ | _vnc from Guacamole_ |
| _TCP_ | _8834_ | _Nessus web UI_ |

## Teamserver ##

| Protocol | Port or Port Range | Reason Needed |
| --- | --- | --- |
| _TCP_ | _22_ | _ssh from Guacamole_ |
| TCP | 25 | Mail |
| TCP | 53 | C2 traffic |
| TCP | 80 | Domain verification |
| TCP | 443 | Payload hosting |
| TCP | 587 | Mail |
| _TCP_ | _993_ | _IMAP_ |
| _TCP_ | _5901_ | _vnc from Guacamole_ |
| TCP | 8000-8999 | Ports that can be manipulated in the event that we need to open a listener for capturing testing traffic from a target.  Default state is not listening. |
| _TCP_ | _50050_ | _CobaltStrike_ |
| UDP | 53 | C2 listening |
| UDP | 8080 | C2 listening/testing |

**Comment by jsf9k** [comment]
cc: @m1j09830, @justinforbes

**Comment by dav3r** [comment]
cc: @sporac, @KyleEvers, @brubach

**Comment by jsf9k** [comment]
@dav3r, you might be the best person to fill out the GoPhish instance type.

**Comment by dav3r** [comment]
> @dav3r, you might be the best person to fill out the GoPhish instance type.

@teal-e and @BenBreaksThings - I filled out the list of publicly-accessible ports needed for COOL GoPhish instances in the table above based on what I have heard in the past.  Please let us know if any modifications are needed to that list.

**Comment by jsf9k** [comment]
@KyleEvers, @justinforbes, and @m1j09830 - regarding the tables above listing the required ports for the teamserver and Kali instances, I see that port 8834 is skipped in the range 8000-8999 of ports that should be accessible.  Since Nessus is not running on those instance, can we change that range to 8000-8999?

**Comment by jsf9k** [comment]
The UFW rules were updated for the teamserver case in cisagov/teamserver-packer#27.

**Comment by m1j09830** [comment]
> > @KyleEvers, @justinforbes, and @m1j09830 - regarding the tables above listing the required ports for the teamserver and Kali instances, I see that port 8834 is skipped in the range 8000-8999 of ports that should be accessible. Since Nessus is not running on those instance, can we change that range to 8000-8999?
> 
> I went ahead and made this change in the issue description above.

@jsf9k that should be fine. There isn't any reason based on our current setup to set aside the nessus port.

**Comment by jsf9k** [comment]
@KyleEvers, @justinforbes, and @m1j09830 - regarding the ports for the teamserver instance above, isn't port 993 (IMAP) only accessed from inside the assessment environment?  Or do you really want external access to IMAP?

**Comment by jsf9k** [comment]
@dav3r, @KyleEvers, @justinfrobes, and @m1j09830 - we currently allow any kind of ICMP packet to ingress to the teamserver, Kali, Nessus, or GoPhish instances.  Is this desired?  Should I restrict this to type 8 only?

**Comment by dav3r** [comment]
> @dav3r, @KyleEvers, @justinfrobes, and @m1j09830 - we currently allow any kind of ICMP packet to ingress to the teamserver, Kali, Nessus, or GoPhish instances. Is this desired? Should I restrict this to type 8 only?

I think type 8 (echo) is most likely sufficient here.

Reference: https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml

**Comment by jsf9k** [comment]
> > @dav3r, @KyleEvers, @justinforbes, and @m1j09830 - we currently allow any kind of ICMP packet to ingress to the teamserver, Kali, Nessus, or GoPhish instances. Is this desired? Should I restrict this to type 8 only?
> 
> I think type 8 (echo) is most likely sufficient here.
> 
> Reference: https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml

Lacking any other input, I'll go with @dav3r's suggestion.

**Comment by m1j09830** [comment]
Sorry @jsf9k for not providing input sooner. I agree with @dav3r that type 8 should be fine.

**Comment by jsf9k** [comment]
@sporac mentioned this morning that port 80 also needs to be open for inbound traffic on the teamserver instances, for domain verification purposes; hence I am reopening this issue.

**Comment by jsf9k** [comment]
Unless @sporac spots any more errors, this issue can be closed when cisagov/cool-assessment-terraform#107 and cisagov/teamserver-packer#29 are merged.

**Comment by jsf9k** [comment]
I'm going to go ahead and close this issue again.  @sporac, if you spot more ports that need to be opened then please reopen this issue.

**Comment by dav3r** [comment]
@justinforbes, @sporac, @KyleEvers, @m1j09830: Do we really need inbound ports 25 and 587 on our Teamserver instances open to the public internet?  I know we send mail outbound from the Teamservers, but do we receive mail on them also?

@cisagov/cyhy-pca: Do we really need inbound ports 25 and 587 on our Gophish instances open to the public internet?  I know we send mail outbound from the Gophish instances, but do we need to receive mail on them also?

If the answer is no, I will re-open this issue and remove access on those inbound ports.

Note that this is related to https://github.com/cisagov/cool-system/issues/90, which will enable us to send all of our assessment-related mail out via a standardized postfix container running on a Gophish instance.  Teamservers will be allowed to send mail out through that postfix container for as long as that functionality is still required (see https://github.com/cisagov/cool-assessment-terraform/issues/111).

**Comment by justinforbes** [comment]
@dav3r Yes we need ports 25 and 587 open because we do need to receive email. We use this for multiple purposes, one is to see how many of the emails we send bounce or get out of office replies. Another reason is that some mail services like O365 will ban us from sending email and we have to receive the email response they send in order to verify our ownership of the domain.

**Comment by dav3r** [comment]
Thanks @justinforbes for confirming that- we will continue to leave those inbound ports open on both our Teamserver and Gophish instances.
