### ISSUE TITLE
Create vmimport role and policy to allow upload of existing images

### ISSUE THREAD

**Issue by felddy** [cisagov/cool-system#181]
# 💡 Summary #

Create `vmimport` role in the image accounts to allow lifting and/or shifting of windows images from the CAL.

## Motivation and context ##

This would be an interim solution until we can get the windows AMIs built using our standard process.

## Implementation notes ##

https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html

This was tested artisanaly in the staging images account.  There were issues with bucket upload timeouts using temporary credentials.

This is the policy that I tested with:

`vmimport` role attached policy in staging account:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3::: example-3rd-party-bucket-staging",
                "arn:aws:s3::: example-3rd-party-bucket-staging/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:GetBucketAcl"
            ],
            "Resource": [
                "arn:aws:s3:::example-3rd-party-bucket-staging",
                "arn:aws:s3::: example-3rd-party-bucket-staging/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:ModifySnapshotAttribute",
                "ec2:CopySnapshot",
                "ec2:RegisterImage",
                "ec2:Describe*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:CreateGrant",
                "kms:Decrypt",
                "kms:DescribeKey",
                "kms:Encrypt",
                "kms:GenerateDataKey*",
                "kms:ReEncrypt*"
            ],
            "Resource": "*"
        }
    ]
}

```

Additionally consider lifecycle rules in the bucket to clean up partial uploads.  

## Acceptance criteria ##

How do we know when this work is done?

- [x] Imported images available in the COOL

**Comment by mcdonnnj** [comment]
After testing the work in https://github.com/cisagov/cool-images-vmimport/pull/1 I was able to use the AWS VM Import/Export feature to import VM images uploaded to the assessment images buckets provided by [cisagov/cool-images-assessment-images](https://github.com/cisagov/cool-images-assessment-images).
