### ISSUE TITLE
Gophish instances locking up

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-system#188]
# 🐛 Summary #

We have seen several instances of COOL Gophish instances becoming unresponsive via both Guacamole VNC and administrative SSH.  This has occurred in both `gophish0.env2` (Staging) and `gophish0.env3` (Production).

## To reproduce ##

1. Deploy a Gophish instance in a COOL assessment environment
2. Wait a while

## Expected behavior ##

The instance should remain accessible by VNC and SSH.

## Any helpful log output or screenshots ##

Output from `/var/log/syslog` on `gophish0.env3` (Production):
```console
Apr 14 13:04:52 ip-10-224-24-234 dockerd[863]: time="2021-04-14T12:55:28.987287654Z" level=error msg="Failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=moby
Apr 14 13:06:15 ip-10-224-24-234 dockerd[863]: time="2021-04-14T12:58:25.021048044Z" level=error msg="Failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
Apr 14 13:08:06 ip-10-224-24-234 dockerd[863]: time="2021-04-14T13:00:48.172009918Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: i/o timeout\". Reconnecting..." module=grpc
Apr 14 13:09:38 ip-10-224-24-234 dockerd[863]: time="2021-04-14T13:00:39.232717350Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Apr 14 13:10:39 ip-10-224-24-234 dhclient[393]: DHCPREQUEST for 10.224.24.234 on ens5 to 10.224.24.1 port 67
Apr 14 13:11:44 ip-10-224-24-234 docker-compose[17872]: #033[32mmailhog_1        |#033[0m [APIv1] KEEPALIVE /api/v1/events
Apr 14 13:13:31 ip-10-224-24-234 dockerd[863]: time="2021-04-14T13:02:20.747089165Z" level=info msg="Waiting for containerd to be ready to restart event processing" module=libcontainerd namespace=moby
Apr 14 13:15:16 ip-10-224-24-234 dockerd[863]: time="2021-04-14T13:03:36.452409023Z" level=info msg="Waiting for containerd to be ready to restart event processing" module=libcontainerd namespace=plugins.moby
Apr 14 13:16:30 ip-10-224-24-234 dhclient[393]: DHCPACK of 10.224.24.234 from 10.224.24.1
Apr 14 13:18:58 ip-10-224-24-234 docker-compose[17872]: #033[32mmailhog_1        |#033[0m [APIv1] KEEPALIVE /api/v1/events
Apr 14 13:22:11 ip-10-224-24-234 dockerd[863]: time="2021-04-14T13:10:58.747401641Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Apr 14 13:24:27 ip-10-224-24-234 dockerd[863]: time="2021-04-14T13:12:43.943162025Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Apr 14 16:32:29 ip-10-224-24-234 kernel: [172070.327829] nfs: server 127.0.0.1 not responding, timed out
Apr 14 16:37:57 ip-10-224-24-234 kernel: [172398.007688] nfs: server 127.0.0.1 not responding, timed out
Apr 14 16:38:03 ip-10-224-24-234 kernel: [172398.007691] nfs: server 127.0.0.1 not responding, timed out
Apr 14 16:38:10 ip-10-224-24-234 kernel: [172398.009007] nfs: server 127.0.0.1 not responding, timed out
Apr 14 16:43:09 ip-10-224-24-234 kernel: [172709.303359] nfs: server 127.0.0.1 not responding, timed out
Apr 14 16:43:16 ip-10-224-24-234 kernel: [172709.303481] nfs: server 127.0.0.1 not responding, timed out
...
```

We have a couple of other issues related to instances hanging- we don't know if this is the same root cause or not, but I'm including those issues here just in case, as suggested by @jsf9k:
* https://github.com/cisagov/cool-system/issues/156
  * I confirmed that the syslog on `gophish0.env3` (Production) did not have any error output similar to [this](https://github.com/cisagov/cool-system/issues/156#issuecomment-769209017) or [this](https://github.com/cisagov/cool-system/issues/156#issuecomment-808242275).
* https://github.com/cisagov/cool-system/issues/125
  * Note similar NFS timeouts mentioned [here](https://github.com/cisagov/cool-system/issues/125#issuecomment-726167514).

**Comment by JCantu248** [comment]
Output from guac.env2.staging

Apr 19 05:54:18 ip-10-224-16-56 kernel: [554638.072120] nfs: server 127.0.0.1 OK
Apr 19 05:54:18 ip-10-224-16-56 kernel: [554638.079109] NFS: nfs4_reclaim_open_state: Lock reclaim failed!
Apr 19 05:54:24 ip-10-224-16-56 dbus-daemon[579]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.102' (uid=0 pid=2426 c
omm="/usr/bin/gdbus call --system --dest org.freedeskto")
Apr 19 05:54:24 ip-10-224-16-56 systemd[1]: Starting PackageKit Daemon...
Apr 19 05:54:24 ip-10-224-16-56 PackageKit: daemon start
Apr 19 05:54:25 ip-10-224-16-56 dbus-daemon[579]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Apr 19 05:54:25 ip-10-224-16-56 systemd[1]: Started PackageKit Daemon.
Apr 19 05:54:31 ip-10-224-16-56 systemd[1]: man-db.service: Succeeded.
Apr 19 05:54:31 ip-10-224-16-56 systemd[1]: Started Daily man-db regeneration.
Apr 19 05:54:49 ip-10-224-16-56 docker-compose[2216]: #033[32mmailhog_1        |#033[0m [APIv1] KEEPALIVE /api/v1/events
Apr 19 05:54:53 ip-10-224-16-56 systemd[1]: apt-daily.service: Succeeded.
Apr 19 05:54:53 ip-10-224-16-56 systemd[1]: Started Daily apt download activities.
Apr 19 05:54:53 ip-10-224-16-56 systemd[1]: Starting Daily apt download activities...
Apr 19 05:54:54 ip-10-224-16-56 systemd[1]: apt-daily.service: Succeeded.
Apr 19 05:54:54 ip-10-224-16-56 systemd[1]: Started Daily apt download activities.
Apr 19 05:54:54 ip-10-224-16-56 systemd[1]: Starting Daily apt upgrade and clean activities...
Apr 19 05:54:56 ip-10-224-16-56 systemd[1]: apt-daily-upgrade.service: Succeeded.
Apr 19 05:54:56 ip-10-224-16-56 systemd[1]: Started Daily apt upgrade and clean activities.
Apr 19 05:55:24 ip-10-224-16-56 freshclam[576]: Mon Apr 19 05:55:24 2021 -> Testing database: '/var/lib/clamav/tmp.a3166/clamav-eaa96862d6ca4817298ef92a20eb5c53.tmp-daily.cld' ...
Apr 19 05:57:58 ip-10-224-16-56 dhclient[486]: XMT: Solicit on ens5, interval 129740ms.
Apr 19 06:58:29 ip-10-224-16-56 kernel: [558488.775046] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:01:30 ip-10-224-16-56 kernel: [558670.023362] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:01:33 ip-10-224-16-56 kernel: [558670.023363] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:01:35 ip-10-224-16-56 kernel: [558674.119365] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:04:37 ip-10-224-16-56 kernel: [558857.383823] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:04:39 ip-10-224-16-56 kernel: [558857.384867] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:04:41 ip-10-224-16-56 kernel: [558857.385855] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:05:39 ip-10-224-16-56 kernel: [558919.080021] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:05:41 ip-10-224-16-56 kernel: [558919.081061] nfs: server 127.0.0.1 not responding, timed out
Apr 19 07:06:54 ip-10-224-16-56 kernel: [558993.608368] nfs: server 127.0.0.1 not responding, still trying

**Comment by jsf9k** [comment]
I'm wondering if the "bad magic" error we see from `stunnel` are not as innocent as we thought so I dug into that.  There is definitely a bug there in a Debian-specific patch that gets applied.  I'm not certain that this issue is the culprit, but I went ahead and [submitted a bug to Debian explaining how to fix the patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987265).

**Comment by dav3r** [comment]
Status update: [Gophish instances built on Bullseye](https://github.com/cisagov/pca-gophish-composition-packer/releases/tag/v0.3.0) have been deployed to one Staging and one Production environment.  They will be tested and monitored to see if this "locking up" issue has been resolved.

The two Staging instances were deployed on April 28 and they have been running without issue since then (almost a week, as of now).  The Production instance was just deployed today (May 4), so we will see what happens (hopefully nothing bad) over the next few days.

**Comment by dav3r** [comment]
This morning, the new Bullseye instance in our Production (user acceptance testing) environment was unresponsive and locked up.  @jsf9k realized that Bullseye does not yet include the patch for the ["bad magic" `stunnel` error](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987265) that [we noted above](https://github.com/cisagov/cool-system/issues/188#issuecomment-823394811), so our next move is to apply that patch in our environment and see what happens.

**Comment by dav3r** [comment]
> This morning, the new Bullseye instance in our Production (user acceptance testing) environment was unresponsive and locked up. @jsf9k realized that Bullseye does not yet include the patch for the ["bad magic" `stunnel` error](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987265) that [we noted above](https://github.com/cisagov/cool-system/issues/188#issuecomment-823394811), so our next move is to apply that patch in our environment and see what happens.

Further testing has revealed that even with the ["bad magic" `stunnel` patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987265) applied on Bullseye, the random lockups were still occurring.  Our next test is to deploy a larger EC2 instance type for Gophish (`t3.medium` instead of `t3.small`) in hopes that going from 2GB to 4GB of RAM helps the situation.  This change was deployed in our Production (user acceptance testing) environment on May 9 and will be monitored.

**Comment by dav3r** [comment]
It looks like upgrading to a `t3.medium` instance fixed whatever the problem was- most likely due to the increase from 2GB to 4GB of RAM.  I created https://github.com/cisagov/cool-assessment-terraform/pull/117 to make this change permanent.  When that PR is merged, it will close this issue.
