### ISSUE TITLE
Resolve remaining compliance scan warnings

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#207]
# 💡 Summary #

There are four remaining compliance scan warnings for the freeIPA and OpenVPN.  These should be resolved by adding the appropriate code to [cisagov/ansible-role-hardening](https://github.com/cisagov/ansible-role-hardening).

The remaining compliance scan warnings are:
- Ensure only strong ciphers are used
- Ensure only strong MAC algorithms are used
- Ensure only strong key exchange algorithms are used
- Ensure access to the `su` command is restricted

## Motivation and context ##

This is required to maintain the COOL ATO.

## Implementation notes ##

See [this document](https://docs.google.com/spreadsheets/d/1EOABdwBPnVmQfhXlOMqLtFxQE54U9GwOdGAJmI0gw1Q/edit#gid=623959049) for more information about these compliance scan warnings.

## Acceptance criteria ##

- [x] A fresh compliance scan run against the FreeIPA and OpenVPN instances no longer contains the the four warnings listed above, or changes them to false positives.
- [x] The FreeIPA and OpenVPN instances continue to function as they did before; the changes made to resolve the compliance scan warnings do not affect the functionality of the instances.

**Comment by jsf9k** [comment]
Verified that the ciphers, MAC algorithms, and key exchange algorithms listed in the example output for FreeIPA (distribution-independent Linux) are precisely the values we have set on the instances.  Therefore this is a false positive for FreeIPA.

**Comment by jsf9k** [comment]
Verified that the ciphers currently configured on the OpenVPN instance _do not_ match the regex listed in the spreadsheet; therefore this finding is a false positive.  Also verified that MAC and key exchange algorithms currently available on the OpenVPN instance _do_ match the regexes listed in the spreadsheet.

For all three cases (ciphers, MACs, and key exchange algorithms) I verified that [the values currently being set for the  FreeIPA instances in cisagov/ansible-role-hardening](https://github.com/cisagov/ansible-role-hardening/blob/a648cec7bf79bb7abf561c7419ab5102652367c3/tasks/18_sshdconfig.yml#L44-L70) are also applicable to the OpenVPN instance.  Hence, I will simply modify the code to apply those changes to both Fedora and Debian.

**Comment by jsf9k** [comment]
The Ansible code for creating an empty group and restricting access to `su` to that group [is already present in the upstream hardening Ansible role](https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/sudo.yml#L88-L107).

**Comment by chelsgr** [comment]
Ticket reopened since OpenVPN is on prod, but FreeIPA is not yet.

**Comment by jsf9k** [comment]
Both OpenVPN and FreeIPA have now been updated in both production and staging.
