### ISSUE TITLE
DNS and SSL Certificates for On Prem Systems

### ISSUE THREAD

**Issue by circuitswitch** [cisagov/cool-system#28]
# 🐛 Bug Report

During migration of DNS resources to the COOL, our On-Prem system lost the ability to use route 53 to validate our certificate requests to Lets Encrypt.  

Previously we used the ACME package in a pfsense system to generate certificates using route 53 to validate the domain.  When the route 53 server was refactored to follow the new COOL architecture, it somehow prevented the pfsense ACME package from using Lets Encrypt.

Please ask COOL technicians for more details, we are only aware of the effect and not the cause.

Please provide a path forward for On-Prem resources to continue operating with valid certificates with as little overhead as possible as we migrate to the COOL.

**Comment by bra1ncramp** [comment]
Is this something you all would like to meet with NOM to discuss? I would like to establish a clear path forward. One of the blockers to implementing our Service Desk is providing a clear URL for users to access. While we can create self-signed certs, as a stop gap, and have the browser warn each time it is accessed, this is not an ideal scenario. I would like to avoid this if possible.

**Comment by felddy** [comment]
@bra1ncramp , I hear you.  I can generate and securely deliver you any certificates you need until we get a long-term process in place...  For each cert you need please provide me a list of of names to include in the SANs of the cert and I'll get it back to you ASAP.  e.g.;

* Cert 1: Ticketing System (production)
  * `jira.ncats.cyber.dhs.gov`
  * `help.ncats.cyber.dhs.gov`
* Cert 2: Ticketing System (staging)
  * `jira-test.ncats.cyber.dhs.gov`
  * `jira.staging.ncats.cyber.dhs.gov`

Something like that...

**Comment by bra1ncramp** [comment]
Mark,Can we just do one cert? Also, I'm trying to use ecdsa if that is possible. This makes maintenance and troubleshooting much easier. If you think we really need to have separate certs for production and staging, then we can do that.Ticketing System (production)jira.ncats.cyber.dhs.govfusion.ncats.cyber.dhs.govTicketing System (staging)jira-test.ncats.cyber.dhs.govservive-test.ncats.cyber.dhs.govOn Apr 17, 2020 10:28 AM, Mark Feldhousen <notifications@github.com> wrote:
@bra1ncramp , I hear you.  I can generate and securely deliver you any certificates you need until we get a long-term process in place...  For each cert you need please provide me a list of of names to include in the SANs of the cert and I'll get it back to you ASAP.  e.g.;
Cert 1: Ticketing System (production)
jira.ncats.cyber.dhs.govhelp.ncats.cyber.dhs.gov
Cert 2: Ticketing System (staging)
jira-test.ncats.cyber.dhs.govjira.staging.ncats.cyber.dhs.gov

Something like that...

**Comment by felddy** [comment]
@bra1ncramp , I hear you about the single cert.  I'll generate a single cert  for both production and staging, but once we move the system off-prem I'd like to revisit this.  

I'd also love to generate an ECDSA cert, but right now we don't support CSRs with [certboto](https://github.com/cisagov/certboto-docker), and `certbot` doesn't have config options to ask for an elliptical curve.  


The good news is that it looks like `certbot` will have ECDSA support soon. (May/June)
See: [certbot TeamGantt](https://prod.teamgantt.com/gantt/schedule/?ids=1448179&public_keys=1yuNAQqvEfSv&zoom=d100&font_size=12&estimated_hours=0&assigned_resources=0&percent_complete=0&documents=0&comments=0&col_width=355&hide_header_tabs=0&menu_view=1&resource_filter=1&name_in_bar=0&name_next_to_bar=0&resource_names=1#user=&company=&custom=&date_filter=&hide_completed=false&color_filter=&ids=1448179)
See: https://github.com/certbot/certbot/issues/6492

I should be able to generate this cert today.

**Comment by bra1ncramp** [comment]
Thank you for the link to certbot support for ECDSA.
Question, what is the likelihood that we could manually generate ECDSA certs if this is not implemented in a timely manner? RSA is rather insecure. However, we do have two servers that can only take RSA certs (Ripley and Mumble). Ripley is on-prem, so should not be of great concern. Mumble may be something we think about, though - since assessments are conducted over it.

**Comment by felddy** [comment]
I'm all for EC as soon as possible.  But it's a bit of a stretch to call 4096 bit RSA keys that are active for 90 days max "rather insecure".   The cash-money isn't being awarded anymore but https://en.wikipedia.org/wiki/RSA_Factoring_Challenge is still being attacked.  

Go get your name in lights and conquer that sweet [862 bit RSA key](https://en.wikipedia.org/wiki/RSA_numbers#RSA-260)  ;)

We'll get there as soon as we can.

**Comment by bra1ncramp** [comment]
You make a fair point. However, have you seen this?https://www.extremetech.com/extreme/173108-researchers-crack-the-worlds-toughest-encryption-by-listening-to-the-tiny-sounds-made-by-your-computers-cpuOn Apr 20, 2020 12:20 PM, Mark Feldhousen <notifications@github.com> wrote:
I'm all for EC as soon as possible.  But it's a bit of a stretch to call 4096 bit RSA keys that are active for 90 days max "rather insecure".   The cash-money isn't being awarded anymore but https://en.wikipedia.org/wiki/RSA_Factoring_Challenge is still being attacked.
Go get your name in lights and conquer that sweet 862 bit RSA key  ;)
We'll get there as soon as we can.

**Comment by felddy** [comment]
All bets are off when you have physical access to the hardware.

**Comment by felddy** [comment]
Certificates were delivered to NOM via Ripley.  

Suggested renaming files when extracted from tarball with something similar to:

`tar xvf jira.ncats.cyber.dhs.gov.tgz --transform='flags=r;s|\.pem|.jira.pem|'`
