### ISSUE TITLE
Windows 10 Instance

### ISSUE THREAD

**Issue by felddy** [cisagov/cool-system#29]

**Comment by sporac** [comment]
I have a few notes about pending Windows 10 image build:
- Both RPT and RVA uses the following software: 
    - Adobe Reader
    - Microsoft Office (PCA currently uses LibreOffice) - used to create templates
    - Mozilla Thunderbird - used to test payloads

AntiVirus should be disabled by default.

**Comment by jsf9k** [comment]
clong/DetectionLab#307 may include some jazz that we need.
