### ISSUE TITLE
PCA ServerSetup Script

### ISSUE THREAD

**Issue by bjb28** [cisagov/cool-system#42]
# 🚀 Feature Proposal

To set up the PCA TeamServer in the legacy method, we will need the ServerSetup Script. In the current setup, the ServerSetup Script is located in `/opt/ServerSetup`.

## Motivation

This script allows the PCA Fed Lead to do the following items inline with our current method:
- Debian Prep to set the FQDN
- Install SSL Keys
- Install mail server
- Email account setup
- Get DKIM information

## Example

Example usage of this script can be seen in our PCA Pre-Assessment Process Run Book. 

## Pitch

This feature will allow the PCA Fed Leads to continue using the current PCA Process.

**Comment by jsf9k** [comment]
@dav3r, do you know if @bjb28 was asking for this functionality for the [cisagov/pca-composition-packer](https://github.com/cisagov/pca-composition-packer) AMI or the [cisagov/teamserver-packer](https://github.com/cisagov/teamserver-packer) AMI?

The ServerSetup script was originally left out of the teamserver AMI (mea culpa), but was added in cisagov/teamserver-packer#17.

**Comment by teal-e** [comment]
This request was only valid if our existing infrastructure we run the Kali VMs on physically in the lab were to go away *before* we had Li-PCAs (that run on GoPhish) fully operational. 

As we still seem to be okay with our existing servers on site, I confirm that our focus is on getting the GoPhish version running in the COOL rather than the legacy version with Cobalt Strike.

**Comment by jsf9k** [comment]
> This request was only valid if our existing infrastructure we run the Kali VMs on physically in the lab were to go away _before_ we had Li-PCAs (that run on GoPhish) fully operational.
> 
> As we still seem to be okay with our existing servers on site, I confirm that our focus is on getting the GoPhish version running in the COOL rather than the legacy version with Cobalt Strike.

So does that mean we can close this issue?

**Comment by dav3r** [comment]
Based on @teal-e's response, I think we can close this issue.
