### ISSUE TITLE
Settings Change required for first-time Viscosity use

### ISSUE THREAD

**Issue by bjb28** [cisagov/cool-system#43]
# 🐛 Bug Report

When logging in for the first time with Viscosity there is no direction to change the `Allow Unsafe OpenVPN commands`. Suggest adding a step 9 to First-time viscosity configuration which directs the user to modify this setting.

## To Reproduce

Follow set up direction. When you reach step 3 of Connect to the COOL VPN you will receive the error. 

## Expected behavior

Expected to connect with no errors.

## Any helpful log output

See image. 

![Viscosity Error](https://user-images.githubusercontent.com/18069368/81940166-4d86d780-95c5-11ea-958f-3822da3a6393.jpeg)

**Comment by dav3r** [comment]
Relates to the content on the [COOL User Login](https://github.com/cisagov/cool-system/blob/develop/guides/users/login.md#first-time-viscosity-configuration) guide (soon to be transitioned to a [COOL Wiki](https://github.com/cisagov/cool-system/wiki) page).
