### ISSUE TITLE
PCA Teamserver Elastic IP

### ISSUE THREAD

**Issue by bjb28** [cisagov/cool-system#45]
# 🚀 Feature Proposal

Request to have an Elastic IP assigned to the PCA Teamserver to prevent us from needing to change DNS records during an assessment. 

## Motivation

Limit the chances that an IP change happens which would require us to update DNS records. If this were to happen we would need to update the customer with the new IP and change DNS records. 

## Example

Same IP through entire assessment.

## Pitch

An elastic IP will help to avoid additional work and possible missed clicks during an assessment.

**Comment by dav3r** [comment]
Issue moved to [cisagov/cool-assessment-terraform #40](https://github.com/cisagov/cool-assessment-terraform/issues/40) via [**ZenHub**](https://www.zenhub.com/)
