### ISSUE TITLE
PCA Teamserver include Thunderbird

### ISSUE THREAD

**Issue by bjb28** [cisagov/cool-system#46]
# 🚀 Feature Proposal

Request to have Thunderbird included on the PCA Teamserver during set up. 

## Motivation

PCA Fed Leads utilize Thunderbird for testing during server set up and customer whitelisting. Additionally Thunderbird is used to ensure proper formatting of phishing emails during campaign setup. 

## Example

- Send test email to Fed Lead trio to check SPF and DKIM.
- Send test email to Customer to ensure Email reaches customer inbox. 
- Send each campaign template to Fed Lead trio to allow us to pull formatting from Thunderbirds original view. 

## Pitch

Thunderbird will allow us to continue operating as we currently do and prevent the need to find new tools/processes.

**Comment by dav3r** [comment]
This was taken care of by @jsf9k in https://github.com/cisagov/teamserver-packer/pull/7.

**Comment by dav3r** [comment]
I think we can close this issue.  @bjb28 if you disagree, please feel free to re-open.
