### ISSUE TITLE
SSL Certificates signed by unknown CA

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/cool-system#48]
# 🐛 Bug Report

Nessus is reporting the following for all infrastructure SSL certs (Example given is only for one server - all have this finding) :
The following certificate was at the top of the certificate
chain sent by the remote host, but it is signed by an unknown
certificate authority :

|-Subject : CN=jira.ncats.cyber.dhs.gov
|-Issuer  : C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

## To Reproduce
Run a basic network scan on the server

## Expected behavior

A validly signing CA

**Comment by dav3r** [comment]
@bra1ncramp - Not sure what is going on here.  When I go to https://jira.ncats.cyber.dhs.gov in my browser, the cert and chain are fully validated.  Are you sure your Nessus is configured properly?

**Comment by bra1ncramp** [comment]
@dav3r , I agree that the cert shows valid in the browser. I think it is possible that Nessus doesn't know the CA. Is it possible to provide (or point to) the CA so we can load it into Nessus?

**Comment by felddy** [comment]
@bra1ncramp For the chain of trust, and the root certs see: https://letsencrypt.org/certificates/

**Comment by bra1ncramp** [comment]
@felddy , we are going to try to load the root CA and re-run the scanner

**Comment by dav3r** [comment]
@bra1ncramp - is this issue still relevant or can it be closed out?

**Comment by bra1ncramp** [comment]
Apologies for not commenting earlier. We simply uploaded  it to the Nessus CA list. We're good now.
