### ISSUE TITLE
Generate SSL Certs for Toolbox

### ISSUE THREAD

**Issue by mzack5020** [cisagov/cool-system#53]
# 💬 Questions and Help

Request to generate SSL certificates for Toolbox. 

CN: toolbox
SAN: toolbox.ncats.cyber.dhs.gov

**Comment by mzack5020** [comment]
@dav3r @felddy

**Comment by dav3r** [comment]
@mzack5020 - The certificate data has been created and placed in `Lab/Certs/` on Ripley.  Please let me know if you have any questions.

**Comment by mzack5020** [comment]
Thank you @dav3r
