### ISSUE TITLE
Old COOL repos use profiles instead of pulling role ARNs from shared state

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#58]
# 🐛 Bug Report

Some of our old, original COOL repositories do not pull role ARNs from remote state but instead use profiles.  These repositories include, but may not be limited to:
* [cool-dns-certboto](https://github.com/cisagov/cool-dns-certboto)
* [cool-images-parameterstore](https://github.com/cisagov/cool-images-parameterstore)
* [cool-sharedservices-networking](https://github.com/cisagov/cool-sharedservices-networking)
* [cool-sharedservices-freeipa](https://github.com/cisagov/cool-sharedservices-freeipa)
* [cool-sharedservices-openvpn](https://github.com/cisagov/cool-sharedservices-openvpn)

(Basically all the things i worked on before you started using remote state in [cool-assessment-terraform](https://github.com/cisagov/cool-assessment-terraform)).

I feel like there could be some of this old foo lurking in [cool-accounts](https://github.com/cisagov/cool-accounts) too, but I didn't find any there when I looked.

**Comment by dav3r** [comment]
The following PRs have removed reliance on local AWS profiles and replaced them with Terraform remote states:
- https://github.com/cisagov/cool-dns-certboto/pull/5
- https://github.com/cisagov/cool-images-parameterstore/pull/11
- https://github.com/cisagov/cool-sharedservices-networking/pull/23
- https://github.com/cisagov/cool-sharedservices-freeipa/pull/17
- https://github.com/cisagov/cool-sharedservices-openvpn/pull/18

I reviewed the [cool-accounts](https://github.com/cisagov/cool-accounts) repo, but didn't see anything that could benefit from remote state usage.
