### ISSUE TITLE
RPT Environment Provisioning

### ISSUE THREAD

**Issue by felddy** [cisagov/cool-system#6]

**Comment by sporac** [comment]
For the RPT environment, aside from the permitted open ports specified in the UAT plan, please also allow inbound tcp/8000-8999. (I'll update the document.)

**Comment by sporac** [comment]
This is minor, but it would better conform to the existing environment.  Can you rename the mount point of the data repository (from /data to /share)?

**Comment by sporac** [comment]
Can you re-add the read-only access to the instances/. They are useful.

**Comment by sporac** [comment]
When will the Nessus instances be added to the environment?
