### ISSUE TITLE
Renew SSL Certs for Infrastructure Servers

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/cool-system#62]
Need renewed SSL certs for the following systems (note, all systems have the ncats.cyber.... domain).

Multi-hostnamed:
1.  jira, jira-test, fusion, service-test
2. yavin, yavin-test

Single host-named:
1. mumble
2. wiki
3. confluence
4. jamf
5. ripley

**Comment by dav3r** [comment]
@bra1ncramp - Per our earlier discussion, I have created fresh certificates for all of the hosts mentioned above and placed them in an encrypted zip file in the usual location on `ripley`.  Please reach out to me via chat for the password.

**Comment by bra1ncramp** [comment]
@dav3r  - yavin's key did not have an alternative hostname of yavin-test

**Comment by dav3r** [comment]
@bra1ncramp - Sorry about that!  There was a typo in the command that I ran to generate that cert, but I didn't notice it.  Anyway, I created a new cert for `yavin` and dropped it in the same directory, with the same password as before.  The new zip is named `yavin.ncats.cyber.dhs.gov_20200717.zip`.

**Comment by bra1ncramp** [comment]
I need new certs generated, please. I somehow missed the expiration date, and they are all needing renewal 
ASAP, please
