### ISSUE TITLE
Force TLS Version 1.2 and up on OpenVPN

### ISSUE THREAD

**Issue by VienCao** [cisagov/cool-system#66]
# 🚀 Feature Proposal

Force TLS Version 1.2 and up for OpenVPN user sessions.

## Motivation

SSL and TLS 1.0 and TLS 1.1 are deprecated

## Example

COOL user sessions would use non-deprecated versions of TLS.

## Pitch

Where my pitches at?

**Comment by jsf9k** [comment]
Assigned to @felddy, as he is our OpenVPN SME.

@felddy if you can't do it, you should reassign it to me.

**Comment by felddy** [comment]
I got this one!
