### ISSUE TITLE
permissions for recon.sh

### ISSUE THREAD

**Issue by sporac** [cisagov/cool-system#69]
The permission for /tool/nlzr/reconnaissance/recon.sh should be set to 755.

As we can change it, it is minor.

**Comment by jsf9k** [comment]
It makes more sense to fix this in [the `nlzr` repo](https://github.com/noahpowers/nlzr), so I [submitted a pull request there](https://github.com/noahpowers/nlzr/pull/5) and will close this issue once that PR gets merged.  At that point, the next Kali AMI that is built will contain the fix.

**Comment by jsf9k** [comment]
My noahpowers/nlzr#5 pull request was closed unmerged, but @noahpowers made the same change himself in noahpowers/nlzr@dfeee8b25554920ee5c365fdae192e79e837c979.  So the fix should appear in the next Kali AMI that is built.

@sporac - I will go ahead and close this issue, but go ahead and reopen it if you still have concerns.  Thanks for reporting this and helping us improve the COOL!
