### ISSUE TITLE
Update to latest release of GoPhish

### ISSUE THREAD

**Issue by teal-e** [cisagov/cool-system#70]
# 🚀 Feature Proposal

Update GoPhish to latest release of v.0.10.1 on May 24, 2020

## Motivation

This release significantly improves the performance of sending emails, adds some features and fixes bugs.

## Example

For large target lists, emails will now be send out significantly faster.

## Pitch

Currently using GoPhish 0.9.x version

**Comment by dav3r** [comment]
This was taken care of via https://github.com/cisagov/pca-gophish-composition/pull/28 and https://github.com/cisagov/gophish-docker/pull/24.
