### ISSUE TITLE
Moving Con-PCA into Cool

### ISSUE THREAD

**Issue by inlguy** [cisagov/cool-system#88]
# 🚀 Feature Proposal
Supplemental to existing #82 
The current Con-PCA application needs migrated from the INL Sandbox to the COOL environment.
Docker
- headless chrome container for reports
- front end container (serves angular application and help system)
- API Django container that services all the api calls
- GoPhish container

Terraform  -- Update terraform to reflect differences between INL Sandbox and COOL
MongoDB -- Run as document DB service (will be handled by Terraform)

## Pitch
As requested for future production.

**Comment by dav3r** [comment]
I believe all work for this has been completed.  @inlguy - please open additional issues if further work is needed.
