### ISSUE TITLE
Develop approach to perform recurring system scans without compromising security

### ISSUE THREAD

**Issue by hillaryj** [cisagov/cool-system#91]
# 🔬 Research

For this task, do some research and planning so we can support scanning the COOL system on a weekly/biweekly basis without leaving up the scanning instances that compromise the locked-down aspects of the system.

## Motivation

- To reduce risk, prefer spinning scanning instances up as needed (instead of leaving them up all the time), although that is a PITA.  This would be less burdensome if someone else (e.g. COOL Security Ops team) could do it themselves.
- Scanning instance jazz is in [cisagov/cool-sharedservices-nessus](https://github.com/cisagov/cool-sharedservices-nessus)
- One approach could be a security deployment (and Organizational Unit?) as a “reference environment”?  Ideally, we could give the COOL Security Ops team the ability to:
    - Spin up/down the environment (at minimum, the scanning instance)
    - Run all necessary scans (vulnerability, compliance, malware)
    - Verify that the instances in the reference environment and those in Production are spun up from the exact same AMI

**Comment by hillaryj** [comment]
Is this task OBE due to VENOM integration?

**Comment by dav3r** [comment]
It should be, but I wouldn't want to close this issue until after we have successfully integrated with VENOM.

**Comment by dav3r** [comment]
@jsf9k - Can we now close this issue?

**Comment by jsf9k** [comment]
I think so, now that Tenable and Tanium are up and running in CDM.
