### ISSUE TITLE
Add Windows 10 VM Image to the COOL

### ISSUE THREAD

**Issue by sei-dspooner** [cisagov/cool-system#97]
# 🚀 Feature Proposal

The assessment teams need access to a current Windows machine with Microsoft Office in order to develop and test phishing payloads.  This could be implemented as a dedicated system per environment, and the teams could accomplish their objectives within the licensing grace period of both Windows and Office.  If licensing costs are still an issue, then this could be implemented as a shared system in env0, assuming the system would have access to the teamservers across all environments.

## Motivation

This replicates functionality that exists in the CAL.

## Pitch

This replicates functionality that exists in the CAL.

**Comment by dav3r** [comment]
May be a duplicate of #29.

**Comment by sei-dspooner** [comment]
Yes, this is a duplicate. Sorry I missed the prior issue.
